/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'auth': RouteRecordInfo<
      'auth',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'experiment': RouteRecordInfo<
      'experiment',
      '/experiment',
      Record<never, never>,
      Record<never, never>,
      | 'experiment-canvas-study'
      | 'experiment-js-up'
      | 'experiment-sticky'
    >,
    'experiment-canvas-study': RouteRecordInfo<
      'experiment-canvas-study',
      '/experiment/canvas-study',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'experiment-js-up': RouteRecordInfo<
      'experiment-js-up',
      '/experiment/js-up',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'experiment-sticky': RouteRecordInfo<
      'experiment-sticky',
      '/experiment/sticky',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'interview': RouteRecordInfo<
      'interview',
      '/interview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/index.vue': {
      routes:
        | 'auth'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/experiment.vue': {
      routes:
        | 'experiment'
        | 'experiment-canvas-study'
        | 'experiment-js-up'
        | 'experiment-sticky'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/experiment/canvas-study.vue': {
      routes:
        | 'experiment-canvas-study'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/experiment/js-up.vue': {
      routes:
        | 'experiment-js-up'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/experiment/sticky.vue': {
      routes:
        | 'experiment-sticky'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/interview.vue': {
      routes:
        | 'interview'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
