/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    'auth': RouteRecordInfo<'auth', '/auth', Record<never, never>, Record<never, never>>,
    'experiment': RouteRecordInfo<'experiment', '/experiment', Record<never, never>, Record<never, never>>,
    'experiment-canvas-study': RouteRecordInfo<'experiment-canvas-study', '/experiment/canvas-study', Record<never, never>, Record<never, never>>,
    'experiment-js-up': RouteRecordInfo<'experiment-js-up', '/experiment/js-up', Record<never, never>, Record<never, never>>,
    'experiment-sticky': RouteRecordInfo<'experiment-sticky', '/experiment/sticky', Record<never, never>, Record<never, never>>,
    'interview': RouteRecordInfo<'interview', '/interview', Record<never, never>, Record<never, never>>,
  }
}
